
name: Prune old workflow runs
on:
  workflow_dispatch:
  schedule:
    # every day at 3am PST
    - cron: "0 10 * * *"

permissions:
  actions: write

jobs:
  prune:
    if: github.repository == 'aptos-labs/aptos-core'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version-file: .node-version
      - run: yarn task pruneGithubWorkflowRuns
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: .github/ts-tasks
